fix: wrong color on button
BeaRoodriguees/lovelace pull request #27
Opened 2024-08-19 13:40 UTC by BeaRoodriguees

# Descrição
- Os botões com gradientes estavam com um bug nas cores.
- O "Lembre-se de mim" e as checkboxes das páginas Login e Register foram comentados

2024-08-19 13:46 UTC, Arthurpmrs requested changes

2024-08-19 13:46 UTC, Arthurpmrs commented on ui/src/components/auth/register-form.module.css
>  .button {
Acho que dá para remover essa linha

2024-08-19 13:49 UTC, Arthurpmrs approved these changes
👍

2024-08-19 23:11 UTC, BeaRoodriguees commented
@daviromao , não avalia ainda não. Percebi o tamanho da logo nessas páginas estão grande demais. Vou ajeitar

2024-08-20 15:51 UTC, daviromao approved these changes
ótima sugestão e deixando um gradient default para tudo.

2024-08-20 15:52 UTC, merged