Upgrade navbar
BeaRoodriguees/lovelace pull request #30
Opened 2024-08-24 13:35 UTC by BeaRoodriguees

# Proposed Changes
- Mudança da componente da Navbar

# Screenshots
Navbar padrão:
![image](https://github.com/user-attachments/assets/a4ec0f2e-6aae-401e-ad8b-80f26db1693f)

Navbar apenas com a logo:
![image](https://github.com/user-attachments/assets/767ea3ef-cbae-434b-9690-2e2a3ead65ff)

Navbar da homepage:
![image](https://github.com/user-attachments/assets/43f2df0b-d20c-4f32-89db-f34da914cc88)

# Ajustes
- [ ] Logo está com um Anchor para a '/problemset', mas quando está deslogado, gostaria de que fosse para '/'

2024-08-24 14:59 UTC, Arthurpmrs requested changes

2024-08-24 14:59 UTC, Arthurpmrs commented on ui/src/app/(auth)/not-found/page.tsx
> +    </>
Acho que aqui poderia ser aquele element `<main></main>` igual você fez para a página de login, achei adequado.

2024-08-24 14:59 UTC, Arthurpmrs commented on ui/src/components/navbar/navbar.tsx
Alguns comentários e sugestões:

1. Quando eu estou logado e acesso a home page, os botões de Entrar e Registrar estão visíveis. Acho que seria melhor ser igual à navbar do problemset.
2. Acho que poderia aumentar o espaçamento entre "Problemas Turmas", search bar e a foto. Além disso, aumentar o constraste entre o link da página ativa e o outro.
3. Acho que seria bom extrair as opções em dois componentes separados (funções no mesmo arquivo), um com os links, searchbar e foto, e outro com os botões de autenticação, poderiam se chamar algo do tipo "NavbarAuthOptions" e "NavbarLoggedOptions".

Por último, só uma sugestão. Essa é mais questão de preferência, não precisa se preocupar tanto. Ao invés de usar o switch, uma opção é fazer algo desse tipo:
```jsx
{status === NavbarStatus.HOME && <NavbarAuthOptions />}
{status === NavbarStatus.LOGGED && <NavbarLoggedOptions />}
```
Somente uma sugestão.

2024-08-25 14:09 UTC, BeaRoodriguees commented on ui/src/components/navbar/navbar.tsx
1. Como eu consigo pegar a informação que o usuário está logado?

3. Acho que não entendi como fazer isso, mas vou procurar

4. Não sabia da existência disso, vou pesquisar sobre e atualizar!

2024-08-25 14:41 UTC, Arthurpmrs commented on ui/src/components/navbar/navbar.tsx
1 - Para verificar se o usuário está logado, você usa essa função aqui:

```js
import { useSession } from 'next-auth/react';
const session = useSession();
const user = session.data?.user
```
Se user for `undefined` o usuário não está logado. Caso contrário vai ser um objeto com as credenciais.

3 - Seria algo desse tipo:

```jsx
function ASubComponent() {
  returnn <button>Opa</button>
}


export default function Navbar() {
   return (
     <div>
       <ASubComponent />
     </div>
  )
}

4 - Blzz

```

2024-08-25 21:35 UTC, Arthurpmrs approved these changes
Aproovad

2024-08-27 00:32 UTC, daviromao requested changes
Muito boa as alterações e funciona corretamente, apontei alguns problemas na questão da acessibilidade.

![image](https://github.com/user-attachments/assets/5ecf4e0f-5c71-4e4a-8785-e42aa048ab18)

2024-08-27 00:32 UTC, daviromao commented on ui/src/app/(auth)/register/page.tsx
> +    </main>
main e navbar

2024-08-27 00:32 UTC, daviromao commented on ui/src/app/(auth)/not-found/page.tsx
> +    </main>
Sobre main e navbar

![image](https://github.com/user-attachments/assets/12f0b0de-fa50-4534-b59b-2f834542fc07)

2024-08-27 00:32 UTC, daviromao commented on ui/src/app/(auth)/login/page.tsx
> +    </main>
a tag main tá relacionada ao conteúdo principal da página, em síntese seria para o texto principal, seguindo a ideia de "html semântico"

remover o <main> da navbar e adicionar <nav> ao conteúdo de navegação da navbar

![image](https://github.com/user-attachments/assets/e16ebdbd-4134-4820-ac15-ad986848835d)

2024-08-27 00:32 UTC, daviromao commented on ui/src/app/page.tsx
>          src="/adaBackground.png"
Forma de verificar se está autenticado, mas já está entendível o código.
![image](https://github.com/user-attachments/assets/53309adb-e426-4ff2-94d8-32c0edb78bae)

2024-08-27 00:32 UTC, daviromao commented on ui/src/components/navbar/navbar.tsx
> +          </Anchor>
A escolha do nome da variável "isLogged" não é uma boa, pois não dá para saber de cara qual o que ela significa.

Contudo, acho que podemos remover essa condição daqui, já que o ícone já existe um "anchor" para problemset quando está logado.

Sempre que houver um anchor em um ícone/imagem, é importante adicionar o aria-label para ele, indicando qual opção ele faz, pois um leitor de texto não consegue identificar qual o ícone

2024-08-27 11:34 UTC, BeaRoodriguees commented on ui/src/app/(auth)/login/page.tsx
> +    </main>
Então eu acho que deveria trocar para um div não? Já que a tag `<main>`  tá juntando a Navbar com o conteúdo da página.

2024-08-27 11:42 UTC, daviromao commented on ui/src/app/(auth)/login/page.tsx
> +    </main>
o div não tem contexto semântico

o ideal é colocar um nav dentro do conteúdo de navegação (componente navbar)

e trazer o main apenas para o conteúdo principal (login form)

2024-08-27 11:58 UTC, BeaRoodriguees commented on ui/src/app/page.tsx
>          src="/adaBackground.png"
Desculpa, acho que não entendi o que quis dizer.

2024-08-27 12:01 UTC, daviromao commented on ui/src/app/page.tsx
>          src="/adaBackground.png"
Apenas mostrei outra forma de verificar se o usuário está autenticado, não tem alterações requisitadas 😄

2024-08-27 12:34 UTC, BeaRoodriguees commented on ui/src/app/(auth)/login/page.tsx
> +    </main>
e eu enrolaria as duas tags com qual tag?

2024-08-28 13:47 UTC, daviromao requested changes

2024-08-28 13:47 UTC, daviromao commented on ui/src/app/(auth)/login/page.tsx
> +      <LoginForm></LoginForm>
```suggestion
      <Navbar status={NavbarStatus.AUTH}></Navbar>
      <main>
            <LoginForm/>
      </main>
```

2024-08-28 13:47 UTC, daviromao commented on ui/src/app/(auth)/not-found/page.tsx
> +      </div>
```suggestion
      <Navbar status={NavbarStatus.AUTH}></Navbar>
      <main className={classes.container}>
        <NotFound></NotFound>
      </main>
```

2024-08-28 13:47 UTC, daviromao commented on ui/src/app/(auth)/register/page.tsx
> +    </>
```suggestion
    <>
      <Navbar status={NavbarStatus.AUTH} />
      <main>
            <RegistrationForm/>
      </main>
    </>
```

2024-08-28 13:47 UTC, daviromao commented on ui/src/app/page.tsx
> +
```suggestion
    {user == undefined && <Navbar status={NavbarStatus.HOME} />}
    {user && <Navbar status={NavbarStatus.LOGGED} />}
    <main className={classes.container}>

```

2024-08-28 13:47 UTC, daviromao commented on ui/src/components/navbar/navbar.tsx
>        <header className={classes.header}>
Usar nav na navbar ao invés de header, apenas sugestão abaixo, alterar para que faça sentido
```suggestion
      <nav className={classes.header}>
```

2024-08-28 21:00 UTC, merged