Criação de componente para Card de Problema
BeaRoodriguees/lovelace pull request #31
Opened 2024-08-25 17:31 UTC by Arthurpmrs

# Related Issue
- #29 

# Proposed Changes
- Desenvolvimento de sub componentes para criação de Cards no sistema
- Criação do componente ProblemCard com base nos subcomponentes

# Checklist
- [x] Desenvolver subcomponentes
- [x] Desenvolver componente ProblemCard
- [x] Responsividade

# Detalhe dos componentes
Cards com diferentes parâmetros
![image](https://github.com/user-attachments/assets/4143d37e-2ecd-40c9-bf5c-2d4aab63980c)

Estrutura do componente
```jsx
<LovelaceCard.Root type={cardType} href={href}>
  <LovelaceCard.Status icon={icon} type={cardType} />
  <LovelaceCard.Content>
    <LovelaceCard.Title text={data.title} />
    <LovelaceCard.Tags tags={data.tags} />
  </LovelaceCard.Content>
  <LovelaceCard.Side label={'Difficulty'} text={data.difficulty} />
  <LovelaceCard.Action
    icon={IconChevronRight}
    type={cardType}
    href={`/problemset/${data.slug}`}
  />
</LovelaceCard.Root>
```

Para usar o componente faça:
```jsx
const data: Problem = {
  id: 'some-id-hash',
  status: ProblemStatus.TODO,
  title: 'Em busca do Ouro Branco',
  tags: ['array', 'pointer', 'eof', 'recursion'],
  difficulty: 'hard',
  slug: 'problem-test',
},

<ProblemCard data={data} />
```

Se quiser que a card como um todo seja clicável, use `<ProblemCard data={data} clickable />`. Nota: Essa opção adiciona um efeito de aumento de escala quando o usuário passa o mouse.

2024-08-25 21:38 UTC, Arthurpmrs commented
Converti para draft, pois percebi que está faltando uma coisa. O componente ProblemCard deve poder receber uma prop `className` como qualquer outro elemento do React. Vou corrigir isso.

2024-08-26 20:16 UTC, BeaRoodriguees approved these changes
Showzinho de bola, meu mano! Ficou mt bom.

(inclusive me ensina)

2024-08-26 21:28 UTC, daviromao requested changes

2024-08-26 21:28 UTC, daviromao commented on ui/src/components/LovelaceCard/LovelaceCardRoot.tsx
> +  );
Por questões de acessibilidade, esse href da forma que foi colocada indica que ao clicar estarei mudando de página? Os exemplos que vi no mantine eles colocavam direto um href, mas imagino que não funciona bem com o que esperamos das navegações do Next.

2024-08-26 21:35 UTC, daviromao commented
![image](https://github.com/user-attachments/assets/74f00c73-d938-46f4-8879-8943a9547df0)

2024-08-27 13:04 UTC, Arthurpmrs commented
## Versão atualizada dos componentes

### Detalhes dos componentes v2
ProblemCard diferentes tipos - dark mode
![image](https://github.com/user-attachments/assets/f548a94c-e34b-4e7f-93c2-d7be2ee45cb2)

ProblemCard diferentes tipos - light mode
![image](https://github.com/user-attachments/assets/109ae0f6-70cc-4499-b4ca-4e8db8dcb7d7)

ProblemCard em foco - navegação por meio da tecla tab
![image](https://github.com/user-attachments/assets/4a08cc03-9254-4fa2-9338-fc22568f4fbb)

ProblemCard em hover - navegação por mouse
![image](https://github.com/user-attachments/assets/5b5a7750-a60f-4b09-9768-ac84ffa1f573)


### Mudanças realizadas
- Cores agora possuem nível de constraste adequado
- Componente ProblemCard agora se comporta como `<Link />`, pelo uso de componentes polimórficos do Mantine.
- Componente ProblemCard é navegáveis através da tecla Tab e mostra um outline adequado quando em foco.

Quando aos sub componentes:
- Subcomponente `LovelaceCard.Root` se comportará como `<Link />`, será clicável e será navegável por meio da tecla tab caso uma prop `href` seja passada.
- Subcomponente `LovelaceCard.Action` agora recebe como parâmetro um callback que é disparado quando o botão é clicado. Caso nenhuma função seja fornecida, ele funcionará apenas como ícone cosmético e não será selecionado quando o usuário navega por meio da tecla tab. O objetivo é dar a possibilidade de criar um botão que tenha outra ação, por exemplo excluir problema de uma lista (no futuro).

Em resumo: Quando se trata de navegação, o Root é transformado em um link. Quando queremos fazer outra ação diferente de navegação, passamos uma função para o Action.

OBS: o `ProblemCard` é um componente que faz uso dos subcomponentes `LovelaceCard`. No caso dele, eu já especifiquei que a card é clicável, passando o como href o link do problema e o botão do Action fica só de enfeite.

2024-08-28 13:55 UTC, daviromao approved these changes
![image](https://github.com/user-attachments/assets/e64ed9b5-45b4-4ea2-af7a-4173bb3156c1)

2024-08-28 13:56 UTC, merged