AB1 + Feature/docker
BeaRoodriguees/lovelace pull request #38
Opened 2024-10-06 13:17 UTC by Arthurpmrs

Tudo da AB1 + docker

Issues relacionadas
- #37 
-

2024-10-09 19:22 UTC, BeaRoodriguees requested changes
Entendi nada. Mas tá tudo lindo!

2024-10-09 19:22 UTC, BeaRoodriguees commented on README.md
> +> A flag `--build` só é necessária quando há uma mudança no código e desejamos reconstruir a imagen e o container.
A palavra 'imagen' está escrita errada! 👍

2024-10-09 19:24 UTC, Arthurpmrs commented on README.md
> +> A flag `--build` só é necessária quando há uma mudança no código e desejamos reconstruir a imagen e o container.
Obrigado, Professora Pasquale.

2024-10-09 19:29 UTC, KeeOtth commented on README.md
> +> A flag `--build` só é necessária quando há uma mudança no código e desejamos reconstruir a imagen e o container.
De fato.

2024-10-09 19:56 UTC, KeeOtth approved these changes
Sim.

2024-10-12 21:21 UTC, BeaRoodriguees approved these changes

2024-10-22 11:58 UTC, filipeferreirasoriano approved these changes
Perfeito!

2024-10-23 13:24 UTC, daviromao approved these changes
![image](https://github.com/user-attachments/assets/5e3460b4-330d-41e4-b230-98939be04c4c)

2024-10-23 13:25 UTC, merged