Adicionando responsividade
BeaRoodriguees/lovelace pull request #43
Opened 2024-10-24 01:07 UTC by BeaRoodriguees

# Related Issue
- #39 
- #36
- #44
- #26 

# Proposed Changes
- Trocado o ícone do Avatar para aparecer iniciais ou foto, caso tenha enviado
- Adicionado menu dropdown
- Adicionado botão de Logout
- Responsividade na navbar (burger com menu dropdown)
- Responsividade na imagem da Ada Lovelace na homepage
- Responsividade no Problemset Header (agora quando a página está pequena o campo de busca diminui e o filtro vira botão de ícone) 
- Início da modularização da página do problema

2024-10-30 20:26 UTC, KeeOtth requested changes
Faltou tratar o comportamento da barra de pesquisa da navbar quando a tela encolhe, fora isso o resto tá okay pra mim.

2024-10-30 21:17 UTC, BeaRoodriguees commented
> Faltou tratar o comportamento da barra de pesquisa da navbar quando a tela encolhe, fora isso o resto tá okay pra mim.

Foi criado a issue #55 para esse problema

2024-10-30 21:19 UTC, KeeOtth approved these changes

2024-10-30 23:31 UTC, Arthurpmrs requested changes
Algumas mudancinhas c:

2024-10-30 23:31 UTC, Arthurpmrs commented on ui/src/components/auth/register-form.tsx
> +              /> */}
Pode deixar esse descomentado

2024-10-30 23:31 UTC, Arthurpmrs commented on ui/src/components/navbar/navbar.tsx
> +      </Menu>
Gostei do que foi feito pro AvatarMenu. Acho que poderia fazer o mesmo com esse. Poderia ser um HamburguerMenu, algo assim

2024-10-30 23:31 UTC, Arthurpmrs commented on ui/src/components/navbar/navbar.tsx
> +          </Menu.Dropdown>
Esse aqui poderia ser um terceiro

2024-10-30 23:31 UTC, Arthurpmrs commented on ui/src/components/problemset/filter-menu.tsx
> +        )}
Acho que aqui daria para fazer algo desse tipo:

```jsx
<Button
    onClick={() =>
        setOpened((o) => {
            toggleFocusTrap();
            return !o;
        })
    }
    leftSection={isMobile ? undefined : <IconFilter stroke={2} />}
    rightSection={
        filterCounter ? <CounterDisplay n={filterCounter} /> : null
    }
    variant={'lovelace-secondary'}
    {...rest}
>
    {isMobile ? <IconFilter size={16} /> : "Filtros"}
</Button>
```

2024-10-30 23:31 UTC, Arthurpmrs commented on ui/src/components/problemset/filter-menu.tsx
> +        )}
Acho que também ficaria melhor um ícone um pouco maior. Acho que size={20} estaria ok

2024-10-30 23:31 UTC, Arthurpmrs commented on ui/src/components/navbar/navbar.tsx
> +      </Menu>
Pode até criar uma pasta navbar-menus para as variações dele

2024-10-31 13:48 UTC, Arthurpmrs approved these changes
LGTM

2024-10-31 13:49 UTC, merged