Integração na página do Problema e Problemset
BeaRoodriguees/lovelace pull request #61
Opened 2024-11-06 20:35 UTC by Arthurpmrs

# Related Issue
- https://github.com/BeaRoodriguees/lovelace/issues/50
- https://github.com/BeaRoodriguees/lovelace/issues/51

# Proposed Changes
- Integração com o backend

# Additional Info
- Maldito Sunbissions... Subsons... Submisssions... Subimissons...

>[!WARNING]
> Não inclui a parte de Submissões.

2024-11-06 22:14 UTC, Arthurpmrs commented
## Problema do Token Expiration

Por algum motivo, os tokens pararam de se renovar sozinhos (ou começaram a expirar) depois de alguma mudança feita recentemente. Isso resulta na impossibilidade de puxar dados do backend, mesmo parecendo que o usuário está logado no frontend (o usuário não era desconectado automaticamente).

Como medida paliativa, configurei o expiration time do token jwt tanto no backend quanto no frontend para 3 dias. Assim, quando o token expira, ele pelo menos faz o logout.

>[!WARNING]
> Importante: o backend puxa o tempo de expiração do token jwt do arquivo .env, então **ATUALIZEM SEUS ARQUIVOS .env LOCAIS.**

2024-11-07 18:30 UTC, KeeOtth approved these changes
Tudo okay meu comandante. 
Todos os bugs foram fixados com sucesso.

2024-11-07 18:37 UTC, BeaRoodriguees requested changes

2024-11-07 18:37 UTC, BeaRoodriguees commented on ui/src/components/problems/problemPage.tsx
> +import { ProblemDetail, Submission } from '@/lib/types';
Foi esquecido de trocar o nome da interface na linha 8 (no types foi trocada para Problem apenas)

2024-11-07 18:37 UTC, BeaRoodriguees commented on ui/src/components/problems/TestCases.tsx
> +import { ProblemDetail } from '@/lib/types';
Aqui (linha 3) também foi esquecido de trocar o nome da interface

2024-11-07 18:37 UTC, BeaRoodriguees commented on ui/src/components/problems/ProblemHeader.tsx
> +import { ProblemDetail } from '@/lib/types';
Aqui tbm falta trocar o nome da interface

2024-11-07 18:37 UTC, BeaRoodriguees commented on ui/src/components/problems/ProblemBody.tsx
> +import { ProblemDetail } from '@/lib/types';
Aqui também faltou trocar o nome da interface

2024-11-07 18:40 UTC, BeaRoodriguees approved these changes

2024-11-07 18:40 UTC, merged